backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img


collections:
  - name: "menus"
    label: "Menus"
    files:
      - file: "src/pages/menus/lunch.md"
        label: "Lunch Menu"
        name: "lunch"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lunch-page"}
          - {label: "Menu", name: "menu", widget: object, fields: [{label: Primi, name: primi, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}, {label: Secondi, name: secondi, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}]}